
version: '3'

services:
  profittrailer:
    image: moli87/pt-notifications-dc
    container_name: pt-notifications
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ./settings.properties:/app/ptnotifications/settings.properties
      - ./database:/app/ptnotifications/database
      - ./logs:/app/ptnotifications/logs
    restart: unless-stopped
