
version: '3'

services:
  ptnotifications:
    build: .
    container_name: pt-notifications-dc
    volumes:
      - ./settings.properties:/app/ptnotifications/settings.properties
      - ./database:/app/ptnotifications/database
      - ./logs:/app/ptnotifications/logs
    restart: always
